# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - houseprice

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_339858e228d742b58f22b4d17a677eb3 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5e0f749ab833411ab3d0219835b3aed6 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_339858e228d742b58f22b4d17a677eb3 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'houseprice'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3ff2dfa9e7974a2089ccf73b7c5f8115 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_339858e228d742b58f22b4d17a677eb3 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}'